name: trunk

on:
  push:
    branches:
      - master
      - main
      - release/*
      - landchecks/*
    tags:
      - ciflow/trunk/*
  workflow_dispatch:

jobs:
  test:
    runs-on: linux.2xlarge
    # If a build is taking longer than 60 minutes on these runners we need
    # to have a conversation
    timeout-minutes: 60
    steps:
      - name: can echo
        run: |
          echo "my change is running"
